version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    semseg:
      image: deephdc/deep-oc-semseg
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    semseg-gpu:
      image: deephdc/deep-oc-semseg:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    semseg-rclone:
      extends:
        service: semseg
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
